spring:
  application:
    name: consumer-service
  freemarker:
    enabled: false # Ignore Eureka dashboard FreeMarker templates

error.path: /error

server.port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DEV ONLY: to speed up registration

# Enable actuator access without security checks
management.endpoints.web.exposure.include: '*'